version: '3.8'

services:
  db:
    image: postgres:17-alpine
    container_name: my_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  api:
    build: .
    container_name: my-api
    ports:
      - "3000:3000"
    environment:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: your_password
      DB_NAME: your_db
      DB_SSLMODE: disable
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
  
  migrate:
    image: migrate/migrate:v4.18.0
    command: ["-path", "/migrations", "-database", "postgres://postgres:your_password@tcp(db:5432)/test?sslmode=disable", "up"]
    volumes:
      - ./migrations:/migrations
    depends_on:
      - db

volumes:
  pgdata: